### PR TITLE
Add zh_tw translation.

### PR DESCRIPTION
**Pull request by s8321414**
I add zh_tw translation here, please review and add it :smile:

### CODE REVIEW

**Comment by brezerk** [comment]
Hi @s8321414 ,

Cool, thanks!

Seems like a typo:
Line: 733 s/WIne/Wine/g

Will fix in the main tree. 
btw: If you wish to add your contacts or info into About / Translators tab feel free to modify src/q4wine-gui/authors.yaml

**Comment by s8321414** [comment]
@brezerk Yes I can, but should I open a new PR?

**Comment by brezerk** [comment]
@s8321414 this one is merged, so yeah, new will be nice.

on the other hand, you can leave your details as an comment here, so I will add them to the authors.yaml for you :)

```
#
# Supported fields are:
#
#        - name: Person's Name
#          nick: Person's nick                      (optional)
#          info: Сontribution to the q4wine project
#          mail: Person's email                     (optional)
#          web: Person's web page                   (optional)
#          jid: Person's jabber account             (optional)
#          location: Person's location              (optional)
```

**Comment by s8321414** [comment]
#        - name: Jeff Huang
#          nick: s8321414
#          info: zh_tw locale translator
#          mail: s8321414@gmail.com
#          web: https://about.me/s8321414
#          location: Taiwan

**Comment by brezerk** [comment]
Thank you :)

**Comment by s8321414** [comment]
@brezerk :+1: :smiley:

**Pull request merged**
